var prjctdir = require('cwd')();
var pkg = require(prjctdir + '/package.json').name.toLowerCase();

module.exports = {
    /* Add NODE_ENV and the main package name */
    generalInfo: function(level, msg, meta) {
        meta.NODE_ENV = process.env.NODE_ENV;
        meta.APP_NAME = pkg;
        return meta;
    },
    /* Add x-request-id if this log message is generated by express-winston */
    xRequestId: function(level, msg, meta) {
        if (meta.req && meta.req.headers && meta.req.headers && meta.req.headers['x-request-id']) {
            meta['x-request-id'] = meta.req.headers['x-request-id'];
        }
        return meta;
    }
}
